In [ ]:
#Q1) CREATE A NUMPY ARRAY OF INTEGER FROM 0 TO 5 AND PRINT ITS TYPE

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
print(arr.dtype)

int64


In [ ]:
#Q2) 2. Given a NumPy array 'arr', check if its data type is float64.

In [ ]:
arr1 = np.array([1.5,2.6,3.7])
arr1

array([1.5, 2.6, 3.7])

In [ ]:
print(arr1.dtype)

float64


In [ ]:
#Q3) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr2 = np.array([1+2j,3+4j,5+6j])
arr2

array([1.+2.j, 3.+4.j, 5.+6.j])

In [ ]:
print(arr2.dtype)

complex128


In [ ]:
#Q4) Convert an existing NumPy array 'arr' of integers to float32 data type

In [ ]:
arr3 = np.array([1,2,3,4,5])
arr4 = arr3.astype(np.float32)
print(arr4)

[1. 2. 3. 4. 5.]


In [ ]:
#Q5)  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
arr5 = np.array([1.23456789, 2.34567890, 3.45678901], dtype=np.float64)
arr6 = arr5.astype(np.float32)

arr6


array([1.2345679, 2.3456788, 3.456789 ], dtype=float32)

In [ ]:
#Q6) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

In [ ]:
def array_attributes(arr7):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

In [ ]:
arr7 = np.array([1,2,3,4,5])
array_attributes(arr7)

((6,), 6, dtype('int64'))

In [ ]:
#Q7)  Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
def array_dimension(arr8):
    dimension = arr8.ndim
    return dimension

In [ ]:
arr8 = np.array([1,2,3,4,5])
array_dimension(arr8)

1

In [ ]:
  #Q8) Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
def item_size_info(arr9):
    item_size = arr9.itemsize
    total_size = arr9.nbytes
    return item_size, total_size

In [ ]:
arr9 = np.array([1,2,3,4,5])
item_size_info(arr9)

(8, 40)

In [ ]:
#Q9) Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
def array_strides(arr10):
    strides = arr10.strides
    return strides

In [ ]:
arr10 = np.array([1,2,3,4,5])
array_strides(arr10)

(8,)

In [ ]:
#Q10)  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
def shape_stride_relationship(arr11):
    shape = arr11.shape
    strides = arr11.strides
    return shape, strides

In [ ]:
arr11 = np.array([1,2,3,4,5])
shape_stride_relationship(arr11)

((5,), (8,))

In [ ]:
#Q11)Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [ ]:
def create_zeros_array(n):
    zeros_array = np.zeros(n)
    return zeros_array

In [ ]:
n =5
create_zeros_array(n)

array([0., 0., 0., 0., 0.])

In [ ]:
#Q)12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [ ]:
def create_ones_matrix(rows, cols):
    ones_matrix = np.ones((rows, cols))
    return ones_matrix

In [ ]:
rows = 3
cols = 4
create_ones_matrix(rows, cols)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
'''
Q13) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`
'''


'\nQ13) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and\ncreates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified\n`step`\n'

In [ ]:
def generate_range_array(start, stop, step):
    range_array = np.arange(start, stop, step)
    return range_array

In [ ]:
start = 1
stop = 10
step = 2
generate_range_array(start, stop, step)

array([1, 3, 5, 7, 9])

In [ ]:
'''
Q)14 Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive)
'''

'\nQ)14 Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as\narguments and generates a NumPy array with num equally spaced values between `start` and `stop`\n(inclusive)\n'

In [ ]:
def generate_linear_space(start, stop, num):
    linear_space = np.linspace(start, stop, num)
    return linear_space

In [ ]:
start = 1.0
stop = 10.0
num = 5
generate_linear_space(start, stop, num)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
'''
Q15) Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.
'''

'\nQ15) Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square\nidentity matrix of size `n x n` using `numpy.eye`.\n'

In [ ]:
def create_identity_matrix(n):
    identity_matrix = np.eye(n)
    return identity_matrix

In [ ]:
n = 3
create_identity_matrix(n)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Q16) Write a function that takes a Python list and converts it into a NumPy array

In [ ]:
def array(lst):
    arr = np.array(lst)
    return arr

In [ ]:
lst = [1,2,3,4,5]
array(lst)

array([1, 2, 3, 4, 5])

In [ ]:
#Q17) Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data

In [ ]:
def numpy_view(arr):
    view_arr = arr[:]
    return view_arr

In [ ]:
arr = np.array([1,2,3,4,5])
numpy_view(arr)

array([1, 2, 3, 4, 5])

In [ ]:
#Q18) Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
def concatenate_arrays(arr1, arr2, axis):
    concatenated_array = np.concatenate((arr1, arr2), axis=axis)
    return concatenated_array

In [ ]:
def concatenate_arrays(arr1, arr2, axis):
    concatenated_array = np.concatenate((arr1, arr2), axis=axis)
    return concatenated_array

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
axis = 0
concatenate_arrays(arr1, arr2, axis)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Q19) Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate`.

In [ ]:
def concatenate_arrays(arr1, arr2, axis):
    concatenated_array = np.concatenate((arr1, arr2), axis=axis)
    return concatenated_array

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6])
axis = 0
concatenate_arrays(arr1, arr2, axis)

array([1, 2, 3, 4, 4, 5, 6])

In [ ]:
#Q20) Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
def vertical_stack(arr_list):
    stacked_array = np.vstack(arr_list)
    return stacked_array

In [ ]:
arr_list = [np.array([1,2,3]), np.array([4,5,6])]
vertical_stack(arr_list)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Q)21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
def create_array(start, stop, step):
    array = np.arange(start, stop, step)
    return array

In [ ]:
start = 1
stop = 10
step = 2
create_array(start, stop, step)

array([1, 3, 5, 7, 9])

In [ ]:
#Q)22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
def generate_array(start, stop, num):
    array = np.linspace(start, stop, num)
    return array

In [ ]:
start = 0
stop = 1
num = 10
generate_array(start, stop, num)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#Q23) Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [ ]:
def create_array(start, stop, num):
    array = np.logspace(start, stop, num)
    return array

In [ ]:
start = 1
stop = 1000
num = 5
create_array(start, stop, num)

/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [ ]:
#Q24) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
def create_dataframe(arr):
    df = pd.DataFrame(arr)
    return df

In [ ]:
arr = np.random.randint(1, 100, size=(5, 3))
create_dataframe(arr)

0   1   2
0  18  23  79
1  13  55  54
2  37  36  33
3  10  53  31
4  53  12  40

In [ ]:
#Q25) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
def replace_negative_values(df, column):
    df.loc[df[column] < 0, column] = 0
    return df

In [ ]:
df = pd.DataFrame({'A': [1, -2, 3, -4], 'B': [-5, 6, -7, 8]})
column = 'A'
replace_negative_values(df, column)

A  B
0  1 -5
1  0  6
2  3 -7
3  0  8

In [ ]:
#Q26) Access the 3rd element from the given NumPy array , arr = np.array([10, 20, 30, 40, 50])

In [ ]:
def access_element(arr, index):
    element = arr[index]
    return element

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
index = 2
access_element(arr, index)

30

In [ ]:
#Q27) Retrieve the element at index (1, 2) from the 2D NumPy array.

In [ ]:
def retrieve_element(arr, index1, index2):
    element = arr[index1, index2]
    return element

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
index1 = 1
index2 = 2
retrieve_element(arr, index1, index2)

6

In [ ]:
#Q28) Using boolean indexing, extract elements greater than 5 from the given NumPy array, arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
def extract_elements(arr, condition):
    elements = arr[condition]
    return elements

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
condition = arr > 5
extract_elements(arr, condition)

array([ 8, 10,  7])

In [ ]:
#Q29) Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array , arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
def perform_slicing(arr, start, stop):
    slicing = arr[start:stop+1]
    return slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
start = 2
stop = 5
perform_slicing(arr, start, stop)

array([3, 4, 5, 6])

In [ ]:
'''
Q30) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

     arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

            '''

'\nQ30) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.\n\n     arr_2d = np.array([[1, 2, 3],\n                   [4, 5, 6],\n                   [7, 8, 9]])\n\n            '

In [ ]:
def slice_2d_array(arr_2d, start_row, end_row, start_col, end_col):
    sub_array = arr_2d[start_row:end_row+1, start_col:end_col+1]
    return sub_array

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
start_row = 0
end_row = 2
start_col = 1
end_col = 3
slice_2d_array(arr_2d, start_row, end_row, start_col, end_col)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
#Q31) Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
def extract_elements(arr, indices):
    elements = arr[indices]
    return elements

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
indices = np.array([1, 0, 2])
extract_elements(arr, indices)

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [ ]:
#Q32)  Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [ ]:
def filter_elements(arr, threshold):
    filtered_arr = arr[arr > threshold]
    return filtered_arr

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5
filter_elements(arr, threshold)

array([ 8, 10,  7])

In [ ]:
'''
#Q)33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.
'''


'\n#Q)33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three\nseparate arrays for each dimension.\n'

In [ ]:
def extract_elements(arr, indices1, indices2, indices3):
    elements = arr[indices1, indices2, indices3]
    return elements

In [ ]:
arr = np.array([[[1, 2,
                  3],
                 [4, 5,
                  6]],
                [[7, 8,
                  9],
                 [10, 11,
                  12]]])
indices1 = np.array([0, 1])
indices2 = np.array([0, 1])
indices3 = np.array([0, 1])
extract_elements(arr, indices1, indices2, indices3)

array([ 1, 11])

In [ ]:
'''
34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.
'''


'\n34. Write a NumPy function that returns elements from an array where both two conditions are satisfied\nusing boolean indexing.\n'

In [ ]:
def return_elements(arr, condition1, condition2):
    elements = arr[condition1 & condition2]
    return elements

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
condition1 = arr > 5
condition2 = arr % 2 == 0
return_elements(arr, condition1, condition2)

array([ 8, 10])

In [ ]:
'''
35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.
'''

'\n35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided\nin separate arrays.\n'

In [ ]:
def extract_elements(arr, indices1, indices2):
    elements = arr[indices1, indices2]
    return elements

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
indices1 = np.array([0, 1])
indices2 = np.array([0, 1])
extract_elements(arr, indices1, indices2)

array([1, 5])

In [ ]:
'''
36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
'''

'\n36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.\n'

In [ ]:
def add_scalar(arr, scalar):
    result = arr + scalar
    return result

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
scalar = 5
add_scalar(arr, scalar)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
'''
37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.
'''

'\n37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the\ncorresponding element in arr1 using NumPy broadcasting.\n'

In [ ]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result = arr1[:, None] * arr2


print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [ ]:
'''
38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.
'''

'\n38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using\nNumPy broadcasting.\n'

In [ ]:
import numpy as np

# Sample arrays
arr1 = np.array([1, 2, 3, 4])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])  # Shape (4, 3)

# Add arr1 to each row of arr2 using broadcasting
result = arr1[:, None] + arr2

# Print the resulting array
print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [ ]:
'''
39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.
'''

'\n39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy\nbroadcasting.\n'

In [ ]:
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4,5,6]])

result = arr1 + arr2

print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#Q41) Calculate column wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)

[2.5 3.5 4.5]


In [ ]:
#Q42) Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)

[3 6]


In [ ]:
#Q43) For the given array, find indices of maximum value in each column.arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr9 = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr9, axis=0)
print(max_indices)

[1 1 1]


In [ ]:
#Q44) For the given array, apply custom function to calculate moving sum along rows.arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
window_size = 2
ones_window = np.ones(window_size)

# Flatten the array for convolution (operates on 1D data)
arr_flat = arr.flatten()

moving_sums = np.convolve(arr_flat, ones_window, mode='same')

# Reshape to recover the original row-wise structure
moving_sums = moving_sums.reshape(arr.shape)

# Print the moving sums
print(moving_sums)


[[ 1.  3.  5.]
 [ 7.  9. 11.]]


In [ ]:
#Q45)In the given array, check if all elements in each column are even.arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
all_even = np.all(arr % 2 == 0, axis=0)
print(all_even)

[False False False]


In [ ]:
#Q46)Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.  array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = arr.reshape(m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Q47)  Create a function that takes a matrix as input and returns the flattened array.  array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
def flatten_matrix(matrix):
    flattened_array = matrix.flatten()
    return flattened_array

In [ ]:
matrix =np.array([1, 2, 3, 4, 5, 6])
flatten_matrix(matrix)

array([1, 2, 3, 4, 5, 6])

In [ ]:
'''
#48) Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
'''

'\n#48) Write a function that concatenates two given arrays along a specified axis.\narray1 = np.array([[1, 2], [3, 4]])\narray2 = np.array([[5, 6], [7, 8]])\n'

In [ ]:
def concat(arr1,arr2,axis =0):
  return np.concatenate((arr1, arr2), axis=axis)

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concat(array1,array2,axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#Q49) Create a function that splits an array into multiple sub-arrays along a specified axis

In [ ]:
def split(arr1):
  return np.split(arr1,3,axis =0)

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split(original_array)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
#Q50) Write a function that inserts and then deletes elements from a given array at specified indices

In [ ]:
def insert_delete(arr, indices,c):
  a1 =  np.insert(arr,1,c,axis=0)
  b1 =  np.delete(arr,[1,3],None)

  return a1,b1

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
indices = [2, 4]
c = [10, 11]
insert_delete(arr,indices,c)

(array([ 1, 10, 11,  2,  3,  4,  5]), array([1, 3, 5]))

In [ ]:
#Q51) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
size = 10


arr1 = np.random.randint(0, 10, size=size)


arr2 = np.random.randint(1, 10,size = size)


result = arr1 + arr2
result

array([ 9,  7, 16,  3,  4,  9, 11,  9,  5, 12])

In [ ]:
#Q52) 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
size = 10


arr1 = np.arange(10, 0,-1)


arr2 = np.random.randint(1, 10,size = size)


result =  arr2 - arr1
result

array([-6, -3, -7,  1, -3, -3, -2,  5,  1,  7])

In [ ]:
#Q53) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
size =10
arr1 = np.random.randint(0, 10, size=size)


arr2 = np.random.randint(1, 5,size = size)


result = arr1 * arr2
result

array([ 6, 28, 27,  5,  0, 32,  3,  2,  0,  6])

In [ ]:
#Q54) Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
size = 20
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2
result

array([2., 2., 2., 2., 2.])

In [ ]:
#Q55)  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
size = 5
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)
result = np.exp(arr1) ** arr2
result

array([ 148.4131591 , 2980.95798704, 8103.08392758, 2980.95798704,
        148.4131591 ])

In [ ]:
'''
Q56)  Write a function that counts the occurrences of a specific substring within a NumPy array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
'''

"\nQ56)  Write a function that counts the occurrences of a specific substring within a NumPy array of strings\narr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])\n"

In [ ]:
def count_substring(arr, substring):
    count = np.sum(np.char.count(arr, substring))
    return count

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count_substring(arr, substring)

3

In [ ]:
'''
57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
'''

"\n57. Write a function that extracts uppercase characters from a NumPy array of strings.\n\narr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])\n"

In [ ]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = np.char.upper(arr)
print(uppercase_characters)

['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [ ]:
'''
58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
'''

'\n58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.\n'

In [ ]:
def replace_substring(arr, old_substring, new_substring):
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'x'
replace_substring(arr, old_substring, new_substring)

array(['x', 'banana', 'grape', 'pinex'], dtype='<U6')

In [ ]:
'''
Q59) Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
'''

"\nQ59) Write a function that concatenates strings in a NumPy array element-wise.\n\narr1 = np.array(['Hello', 'World'])\narr2 = np.array(['Open', 'AI'])\n"

In [ ]:
def concatenate_strings(arr1, arr2):
    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenate_strings(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
'''
Q60) 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
'''

"\nQ60) 60. Write a function that finds the length of the longest string in a NumPy array.\n\narr = np.array(['apple', 'banana', 'grape', 'pineapple'])\n"

In [ ]:
def longest_string_length(arr):

    string_list = arr.tolist()


    max_length = max(len(s) for s in string_list)

    return max_length


In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))

9


In [ ]:
'''
#Q61) Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.
'''

"\n#Q61) Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and\nstandard deviation of the dataset using NumPy's functions.\n"

In [ ]:
def compute_statistics(data):
    mean = np.mean(data)
    median = np.median(data)
    variance = np.var(data)
    std_dev = np.std(data)
    return mean, median, variance, std_dev

In [ ]:
data = np.random.randint(1, 1000, size=100)
compute_statistics(data)

(540.33, 514.0, 72094.5211, 268.5042292031915)

In [ ]:
#Q62) Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
arr = np.random.randint(1, 100, size=50)
percentile_25 = np.percentile(arr, 25)
percentile_75 = np.percentile(arr, 75)

In [ ]:
percentile_25

26.75

In [ ]:
percentile_75

75.5

In [ ]:
#Q63) Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
correlation_coefficient = np.corrcoef(arr1, arr2)
correlation_coefficient

array([[1., 1.],
       [1., 1.]])

In [ ]:
#Q64) Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
matrix_multiplication = np.dot(arr1, arr2)
matrix_multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
#Q65) Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [ ]:
arr = np.random.randint(10, 1000, size=50)
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)
percentile_90 = np.percentile(arr, 90)  # 90th percentile
first_quartile = np.percentile(arr, 25)  # First quartile
third_quartile = np.percentile(arr, 75)  # Third quartile

In [ ]:
percentile_10

56.900000000000006

In [ ]:
percentile_50

475.0

In [ ]:
percentile_90

889.4

In [ ]:
first_quartile

216.75

In [ ]:
third_quartile

737.25

In [ ]:
#Q66) Create a NumPy array of integers and find the index of a specific element.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
element_index = np.where(arr == 3)
element_index

(array([2]),)

In [ ]:
#67) Generate a random NumPy array and sort it in ascending order.

In [ ]:
arr = np.random.rand(10)
sorted_arr = np.sort(arr)
sorted_arr


array([0.03475953, 0.05507647, 0.07180353, 0.16642139, 0.26099149,
       0.27433175, 0.35077109, 0.35958041, 0.37541913, 0.88436948])

In [ ]:
'''
68) 68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])
'''

'\n68) 68. Filter elements >20  in the given NumPy array.\n\narr = np.array([12, 25, 6, 42, 8, 30])\n'

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
filtered_arr

array([25, 42, 30])

In [ ]:
'''
69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
'''

'\n69. Filter elements which are divisible by 3 from a given NumPy array.\narr = np.array([1, 5, 8, 12, 15])\n'

In [ ]:
arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
filtered_arr

array([12, 15])

In [ ]:
'''
70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
'''

'\n70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.\n'

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

b = np.logical_and(arr >= 20, arr <= 40)

c = arr[b]

c

array([20, 30, 40])

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
'''
Q71)  For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])
'''

'\nQ71)  For the given NumPy array, check its byte order using the `dtype` attribute byteorder.\n\narr = np.array([1, 2, 3])\n'

In [ ]:
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
byte_order

'='

In [ ]:
'''
72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1, 2, 3], dtype=np.int32)

'''

'\n72. For the given NumPy array, perform byte swapping in place using `byteswap()`.\n\narr = np.array([1, 2, 3], dtype=np.int32)\n\n'

In [ ]:
arr = np.array([1,2,3], dtype = np.int32)
arr.byteswap(inplace=True)
arr

array([16777216, 33554432, 50331648], dtype=int32)

In [ ]:
'''
73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

'''

'\n73. For the given NumPy array, swap its byte order without modifying the original array using\n`newbyteorder()`.\n\narr = np.array([1, 2, 3], dtype=np.int32)\n\n'

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
new_byte_order = arr.newbyteorder()
new_byte_order

array([16777216, 33554432, 50331648], dtype='>i4')

In [ ]:
'''
74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
'''

'\n74. For the given NumPy array and swap its byte order conditionally based on system endianness using\n`newbyteorder()`.\narr = np.array([1, 2, 3], dtype=np.int32)\n'

In [ ]:
import numpy as np
import sys

# Define the NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check system endianness
if sys.byteorder == 'little':
    # If the system is little-endian, convert to big-endian
    swapped_arr = arr.newbyteorder('>')
else:
    # If the system is big-endian, convert to little-endian
    swapped_arr = arr.newbyteorder('<')

# Display the original and the swapped arrays
print("Original array:", arr)
print("Byte-swapped array:", swapped_arr)


Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [ ]:
'''
Q75) For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.
'''

'\nQ75) 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`\nattribute `byteorder`.\n'

In [ ]:
import numpy as np
import sys

# Define the NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Determine the system's endianness
system_endianness = sys.byteorder  # 'little' or 'big'

# Determine the array's byte order
array_byteorder = arr.dtype.byteorder

# Check if byte swapping is necessary
needs_swapping = False

if array_byteorder == '=':
    # '=' means native byte order, which is the same as the system's byte order
    needs_swapping = False
elif (system_endianness == 'little' and array_byteorder != '<') or \
     (system_endianness == 'big' and array_byteorder != '>'):
    # If system is little-endian and array is not little-endian or
    # system is big-endian and array is not big-endian, swapping is needed
    needs_swapping = True

# Output the results
print(f"System Endianness: {system_endianness}")
print(f"Array Byte Order: {array_byteorder}")
print(f"Needs Byte Swapping: {needs_swapping}")


System Endianness: little
Array Byte Order: =
Needs Byte Swapping: False


In [ ]:
'''
Q76) 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
'''

'\nQ76) 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify\nan element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.\n'

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
copy_arr = arr1.copy(order = 'C')
copy_arr[0] = 100
print(arr1)
print(copy_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]
